### ISSUE TITLE
Question about performance

### ISSUE THREAD

**Issue by EdanToledo** [ACEsuit/mace-jax#5]
Hello,

I was just wondering why you state that training is more optimal on the pytorch implementation?

**Comment by ilyes319** [comment]
Hey, 
Not more optimal in a computational sense, but more updated and well tested as this is the one that we have used the most internally. In principle the jax should work well aswell and is also fairly well tested.

**Comment by EdanToledo** [comment]
Thank you so much for the quick answer!!
